[tool.poetry]
name = "db-eplusout-reader"
version = "0.2.0"
description = ""
authors = ["Vojtech Panek <vojtech.panek@designbuilder.co.uk>"]

[tool.poetry.dependencies]
python = "^2.7"

[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
